version: '3'
services:
  flask:
    # 
    build:
    # 
    container_name: flask_app
    # 
    restart: on-failure
    # 
    volumes:
      - ./app:/app
      # 
      ports:
        - "5000:5000"
